variables:
  GIT_SUBMODULE_STRATEGY: recursive

stretch-amd64: &desktop_template
  image: slavanap/ros-build:stretch-amd64
  stage: build
  tags:
    - docker
  script:
    - &prep_environment |
      mkdir /tmp/build && ln -s "$PWD" /tmp/build/src && cd /tmp/build
      source "/opt/ros/$ROS_DISTRO/setup.bash"
    - catkin_make_isolated --install --install-space "/opt/ros/sweetie_bot" -DCMAKE_BUILD_TYPE=Release -DLOGGER_DEFAULT=LoggerRosout
    - &buildpkg |
      source "/tmp/repo/buildpkg.bash"
      export BASE_VERSION="$DEB_VERSION"
      export DEB_VERSION="${DEB_VERSION%~*}-${CI_JOB_ID}~${DEB_VERSION#*~}"
      export DEB_NAME="ros-${ROS_DISTRO}-sweetie-bot$PKG_SUFFIX"
      export DEB_DESCRIPTION="Package $DEB_NAME for $ROS_DISTRO" \
        DEB_HOMEPAGE="http://sweetiebot.net/"
      buildpkg "/opt/ros/sweetie_bot" "sweetie-bot.deb" "ros-${ROS_DISTRO}-sweetie-bot-base$PKG_SUFFIX (=${BASE_VERSION})" || echo "ret code $?"
      mv "sweetie-bot.deb" "$CI_PROJECT_DIR/sweetie-bot-${CI_JOB_NAME}-${CI_JOB_ID}.deb"
      mv /tmp/repo/sweetie-bot-base.deb "$CI_PROJECT_DIR/sweetie-bot-base-${CI_JOB_NAME}-${CI_JOB_ID}.deb"
  artifacts:
    name: "deb package"
    expire_in: 3 weeks
    paths:
      - "sweetie-bot-*.deb"

xenial-amd64:
  <<: *desktop_template
  image: slavanap/ros-build:xenial-amd64

stretch-rpi3: &robot_template
  <<: *desktop_template
  image: slavanap/ros-build:stretch-rpi3
  script:
    - touch hmi/sweetie_bot_rviz_interactions/CATKIN_IGNORE hmi/sweetie_bot_joint_trajectory_editor/CATKIN_IGNORE behavior/sweetie_bot_voice/CATKIN_IGNORE
    - *prep_environment
    - catkin_make_isolated $CMAKE_TOOLCHAIN --install --install-space "/opt/ros/sweetie_bot" -DCMAKE_BUILD_TYPE=Release -DLOGGER_DEFAULT=LoggerRosout
    - *buildpkg

xenial-tinker:
  <<: *robot_template
  image: slavanap/ros-build:xenial-tinker

xenial-xeon:
  <<: *desktop_template
  image: slavanap/ros-build:xenial-xeon
