stretch-amd64: &desktop_template
  stage: build
  image: registry.gitlab.com/slavanap/ros-build:stretch-amd64
  tags:
    - docker
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - &prep_environment |
      mkdir /tmp/build && ln -s "$PWD" /tmp/build/src && cd /tmp/build
      source "/opt/ros/$ROS_DISTRO/setup.bash"
    - catkin_make_isolated --install --install-space "/opt/ros/sweetie_bot" -DCMAKE_BUILD_TYPE=Release -DLOGGER_DEFAULT=LoggerRosout
    - &buildpkg |
      source "/tmp/repo/buildpkg.bash"
      export BASE_VERSION="$DEB_VERSION"
      export DEB_VERSION="${DEB_VERSION%~*}-${CI_JOB_ID}~${DEB_VERSION#*~}"
      export DEB_NAME="ros-${ROS_DISTRO}-sweetie-bot$PKG_SUFFIX"
      export DEB_DESCRIPTION="Package $DEB_NAME for $ROS_DISTRO" \
        DEB_HOMEPAGE="http://sweetiebot.net/"
      buildpkg "/opt/ros/sweetie_bot" "sweetie-bot.deb" "ros-${ROS_DISTRO}-sweetie-bot-base$PKG_SUFFIX (=${BASE_VERSION})" || echo "ret code $?"
      mv "sweetie-bot.deb" "$CI_PROJECT_DIR/sweetie-bot-${CI_JOB_NAME}-${CI_JOB_ID}.deb"
      mv /tmp/repo/sweetie-bot-base.deb "$CI_PROJECT_DIR/sweetie-bot-base-${CI_JOB_NAME}-${CI_JOB_ID}.deb"
  artifacts:
    name: sweetie-bot-${CI_JOB_NAME}
    expire_in: 3 weeks
    paths:
      - "sweetie-bot-*.deb"

xenial-amd64:
  <<: *desktop_template
  image: registry.gitlab.com/slavanap/ros-build:xenial-amd64

stretch-rpi3: &robot_template
  <<: *desktop_template
  image: registry.gitlab.com/slavanap/ros-build:stretch-rpi3
  script:
    - touch hmi/sweetie_bot_rviz_interactions/CATKIN_IGNORE hmi/sweetie_bot_joint_trajectory_editor/CATKIN_IGNORE behavior/sweetie_bot_voice/CATKIN_IGNORE
    - *prep_environment
    - catkin_make_isolated $CMAKE_TOOLCHAIN --install --install-space "/opt/ros/sweetie_bot" -DCMAKE_BUILD_TYPE=Release -DLOGGER_DEFAULT=LoggerRosout
    - *buildpkg

xenial-tinker:
  <<: *robot_template
  image: registry.gitlab.com/slavanap/ros-build:xenial-tinker

xenial-amd64-test: &test_template
  stage: test
  image: docker:stable-git
  services:
    - docker:dind
  tags:
    - docker
  dependencies:
    - xenial-amd64
  variables: &test_vars
    CONTAINER_IMAGE: registry.gitlab.com/${CI_PROJECT_PATH}:${CI_JOB_NAME}-cache
    DOCKER_HOST: tcp://docker:2375/
    IMAGE_SOURCE: ubuntu:xenial
  script:
    - ls -la
    - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" registry.gitlab.com
    - git clone https://gitlab-ci-token:$CI_JOB_TOKEN@gitlab.com/sweetie-bot/sweetie_bot_flexbe_behaviors.git .gitlab-ci/sweetie_bot_flexbe_behaviors
    - git clone https://gitlab-ci-token:$CI_JOB_TOKEN@gitlab.com/sweetie-bot/sweetie_bot_proto2_movements.git .gitlab-ci/sweetie_bot_proto2_movements
    - git clone https://gitlab-ci-token:$CI_JOB_TOKEN@gitlab.com/sweetie-bot/sweetie_bot_sounds.git .gitlab-ci/sweetie_bot_sounds

    - |
      if ( docker pull "$CONTAINER_IMAGE" && \
        docker run -i --name prev "$CONTAINER_IMAGE" sh -c 'mv sweetie-bot-base*.deb prev.deb' && \
        docker cp prev:/home/dev/prev.deb . && \
        cmp prev.deb sweetie-bot-base*.deb )
      then
        rm prev.deb; docker rm prev
        docker build -t "$CONTAINER_IMAGE" --build-arg IMAGE_SOURCE="$CONTAINER_IMAGE" -f .gitlab-ci/test-fromcache.dockerfile .
      else
        rm prev.deb || true; docker rm prev || true
        docker build -t "$CONTAINER_IMAGE" --build-arg IMAGE_SOURCE="$IMAGE_SOURCE" -f .gitlab-ci/test-init.dockerfile .
        docker push "$CONTAINER_IMAGE"
      fi      
    - docker build -t test --build-arg IMAGE_SOURCE="$CONTAINER_IMAGE" -f .gitlab-ci/test.dockerfile .
    - docker create --name temp test
    - docker cp temp:/home/dev/retcode .
    - docker cp temp:/home/dev/screenshot.png . || true
    - docker cp temp:/home/dev/diff.png . || true
    - docker cp temp:/home/dev/.ros/log ./__log || true
    - ( exit $(cat ./retcode || echo 42) )
  artifacts:
    expire_in: 3 weeks
    paths:
      - screenshot.png
      - diff.png
      - __log/
    when: always

stretch-amd64-test:
  <<: *test_template
  dependencies:
    - stretch-amd64
  variables:
    <<: *test_vars
    IMAGE_SOURCE: debian:stretch
