before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive

desktop-stretch:
  image: slavanap/compile_orocos:lunar-stretch
  stage: build
  tags:
    - docker
  script:
    - export ROS_PARALLEL_JOBS=-j3
    - ( mkdir -p /tmp/repo/sweetie_bot || true ) && ln -s "$PWD" /tmp/repo/sweetie_bot/src
    - ( cd /tmp/repo && ./travis.bash sweetie-bot-pkg )
    - mv /tmp/repo/sweetie-bot.deb ./ 
  artifacts:
    name: "$CI_JOB_NAME.deb"
    expire_in: 3 weeks
    paths:
      - sweetie-bot.deb

desktop-xenial:
  image: slavanap/compile_orocos:lunar-xenial
  stage: build
  tags:
    - docker
  script:
    - ( mkdir -p /tmp/repo/sweetie_bot || true ) && ln -s "$PWD" /tmp/repo/sweetie_bot/src
    - ( cd /tmp/repo && ./travis.bash sweetie-bot-pkg )
    - mv /tmp/repo/sweetie-bot.deb ./ 
  artifacts:
    name: "$CI_JOB_NAME.deb"
    expire_in: 3 weeks
    paths:
      - sweetie-bot.deb

rpi3-stretch:
  image: slavanap/compile_orocos:lunar-stretch-rpi3
  stage: build
  tags:
    - docker-armhf
  script:
    - ( mkdir -p /tmp/repo/sweetie_bot || true ) && ln -s "$PWD" /tmp/repo/sweetie_bot/src
    - ( cd /tmp/repo && ./travis.bash sweetie-bot-pkg )
    - mv /tmp/repo/sweetie-bot-rpi3.deb ./ 
  artifacts:
    name: "$CI_JOB_NAME.deb"
    expire_in: 3 weeks
    paths:
      - sweetie-bot-rpi3.deb
