controller_list:
  - name: motion/controller
    action_ns: joint_trajectory
    type: FollowJointTrajectory
    default: true 
    joints:
      - joint11
      - joint12
      - joint13
      - joint14
      - joint15
      - joint16
      - joint21
      - joint22
      - joint23
      - joint24
      - joint25
      - joint26
      - joint31
      - joint32
      - joint33
      - joint34
      - joint35
      - joint36
      - joint41
      - joint42
      - joint43
      - joint44
      - joint45
      - joint46
      - joint51
      - joint52
      - joint53
      - joint54
