controller_list:
  - name: fake_leg1_controller
    joints:
      - leg1_joint1
      - leg1_joint2
      - leg1_joint3
      - leg1_joint4
      - leg1_joint5
      - leg1_joint6
  - name: fake_leg2_controller
    joints:
      - leg2_joint1
      - leg2_joint2
      - leg2_joint3
      - leg2_joint4
      - leg2_joint5
      - leg2_joint6
  - name: fake_leg3_controller
    joints:
      - leg3_joint1
      - leg3_joint2
      - leg3_joint3
      - leg3_joint4
      - leg3_joint5
      - leg3_joint6
  - name: fake_leg4_controller
    joints:
      - leg4_joint1
      - leg4_joint2
      - leg4_joint3
      - leg4_joint4
      - leg4_joint5
      - leg4_joint6
  - name: fake_head_controller
    joints:
      - head_joint1
      - head_joint2
      - head_joint3
      - head_joint4
  - name: fake_legs_controller
    joints:
      - leg1_joint1
      - leg1_joint2
      - leg1_joint3
      - leg1_joint4
      - leg1_joint5
      - leg1_joint6
      - leg2_joint1
      - leg2_joint2
      - leg2_joint3
      - leg2_joint4
      - leg2_joint5
      - leg2_joint6
      - leg3_joint1
      - leg3_joint2
      - leg3_joint3
      - leg3_joint4
      - leg3_joint5
      - leg3_joint6
      - leg4_joint1
      - leg4_joint2
      - leg4_joint3
      - leg4_joint4
      - leg4_joint5
      - leg4_joint6
  - name: fake_all_controller
    joints:
      - head_joint1
      - head_joint2
      - head_joint3
      - head_joint4
      - leg1_joint1
      - leg1_joint2
      - leg1_joint3
      - leg1_joint4
      - leg1_joint5
      - leg1_joint6
      - leg2_joint1
      - leg2_joint2
      - leg2_joint3
      - leg2_joint4
      - leg2_joint5
      - leg2_joint6
      - leg3_joint1
      - leg3_joint2
      - leg3_joint3
      - leg3_joint4
      - leg3_joint5
      - leg3_joint6
      - leg4_joint1
      - leg4_joint2
      - leg4_joint3
      - leg4_joint4
      - leg4_joint5
      - leg4_joint6