resource_control:
    arbiter:
        priority: 20
        resources: [ leg1, leg2, leg3, leg4, head, eyes, tail, eyes_focus ]
agregator_ref: 
    priority: 20
servo_inv:
    priority: 20
    lead: 0.056
agregator_real:
    priority: 20
kinematics_fwd:
    priority: 20
    kinematic_chains: [ leg1, leg3, leg4, leg2, head ]
odometry_ref:
    priority: 20
    legs: [ leg1, leg3, leg4, leg2 ]
    force_contact_z_to_zero: true
timer:
    priority: 45
    period: 0.056
