controller:
    joint_state:
        priority: 20
        controlled_chains: [ leg1, leg2, leg3, leg4, head, eyes, eyes_focus ]
        activation_delay: 2
        services: [ filter_joint_state_exp ]
        filter_joint_state_exp:
            transient_time: 1
    joint_state_head:
        priority: 20
        controlled_chains: [ head, eyes, eyes_focus ]
        activation_delay: 2
        services: [ filter_joint_state_exp_individual ]
        filter_joint_state_exp_individual:
            transient_time: 1
            joints_override: [ joint55, joint56 ]
            transient_time_override: [ 0.3, 0.3 ]
    joint_trajectory: 
        priority: 20
        services: [ transient_joint_state_exp ]
        transient_joint_state_exp:
            transient_time: 0.5
    torque_off: 
        priority: 20
        herkulex_scheds: [ herkulex/sched ]
        herkulex_arrays: [ herkulex/array ]
        velocity_zeroing: true
