controller_list:
  - name: fake_leg1_controller
    joints:
      - joint11
      - joint12
      - joint13
      - joint14
      - joint15
  - name: fake_leg2_controller
    joints:
      - joint21
      - joint22
      - joint23
      - joint24
      - joint25
  - name: fake_leg3_controller
    joints:
      - joint31
      - joint32
      - joint33
      - joint34
      - joint35
  - name: fake_leg4_controller
    joints:
      - joint41
      - joint42
      - joint43
      - joint44
      - joint45
  - name: fake_head_controller
    joints:
      - joint51
      - joint52
      - joint53
      - joint54
  - name: fake_legs_controller
    joints:
      - joint11
      - joint12
      - joint13
      - joint14
      - joint15
      - joint21
      - joint22
      - joint23
      - joint24
      - joint25
      - joint31
      - joint32
      - joint33
      - joint34
      - joint35
      - joint41
      - joint42
      - joint43
      - joint44
      - joint45
  - name: fake_all_controller
    joints:
      - joint11
      - joint12
      - joint13
      - joint14
      - joint15
      - joint21
      - joint22
      - joint23
      - joint24
      - joint25
      - joint31
      - joint32
      - joint33
      - joint34
      - joint35
      - joint41
      - joint42
      - joint43
      - joint44
      - joint45
      - joint51
      - joint52
      - joint53
      - joint54
  - name: fake_legs_front_controller
    joints:
      - joint11
      - joint12
      - joint13
      - joint14
      - joint15
      - joint21
      - joint22
      - joint23
      - joint24
      - joint25